language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - npm prune
  - "sudo chown root /usr/lib/chromium-browser/chrome-sandbox"
  - "sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox"
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - npm run ci
