language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
  - "sudo chown root /usr/lib/chromium-browser/chrome-sandbox"
  - "sudo chmod 4755 /usr/lib/chromium-browser/chrome-sandbox"
  - npm run start
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  - npm run ci
