import { Component }                                                             from '@angular/core';
import { IonicPage, NavController, NavParams, ViewController, AlertController }  from 'ionic-angular';

/**
 * A dialog that allows users to add masks.
 */
@IonicPage()
@Component({
  selector: 'page-add-mask',
  templateUrl: 'add-mask.html',
})
export class AddMaskPage {

  /**
   * The name of the new mask.
   **/
   newMaskName: string;

  /**
   * Inject dependencies.
   */
  constructor(public navCtrl: NavController, public navParams: NavParams, public viewController: ViewController, public alertController: AlertController ) { }

  /**
   * Boilerplate generated by the framework.
   */
  ionViewDidLoad() {
    console.log('ionViewDidLoad AddMaskPage');
  }

  /**
   * Implements the cancel button.
   */
  public cancel(): void {
    let alert = this.alertController.create({
      title: "Discard new mask?",
      buttons: [
        {
          text: 'cancel',
          role: 'cancel'
        },
        {
          text: 'delete',
          handler: () => { this.viewController.dismiss(); }
        }
      ]
    });
    alert.present();
  }

  /**
   * Implements the save button.
   */
  public save(): void {
    if (this.newMaskName) {
      this.viewController.dismiss(this.newMaskName);
    }
    else {
      let alert = this.alertController.create({
        title: "You need to give the new mask a name.",
        buttons: ['dismiss']
      });

      alert.present();
    }
  }

}
